# Generated by Django 6.0.6 on 2026-06-24 10:39

from django.db import migrations


def create_categories(apps, schema_editor):
    Category = apps.get_model("dashboard", "Category")

    categories = [
        ("Lighting Automation", "Lighting automation includes all products involved in smart lighting systems."),
        ("Window / Curtain Automation", "Automated systems for curtains, blinds, and window control."),
        ("Door Automation", "Smart locks, automatic doors, and access control systems."),
        ("Water Automation", "Pump control, valves, irrigation, and water flow automation systems."),
        ("Rolling Shutter Automation", "Motorized rolling shutter systems and controllers."),
    ]

    for name, desc in categories:
        Category.objects.get_or_create(
            name=name,
            defaults={"description": desc},
        )


def reverse_func(apps, schema_editor):
    Category = apps.get_model("dashboard", "Category")
    Category.objects.filter(
        name__in=[
            "Lighting Automation",
            "Window / Curtain Automation",
            "Door Automation",
            "Water Automation",
            "Rolling Shutter Automation",
        ]
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(create_categories, reverse_func),
    ]
